export const PERMISSION_MATRIX = {
  users: {
    VIEW: 'users.view',
    CREATE: 'users.create',
    UPDATE: 'users.update',
    DELETE: 'users.delete',
    APPROVE: 'users.approve',
  },
  departments: {
    VIEW: 'departments.view',
    CREATE: 'departments.create',
    UPDATE: 'departments.update',
    DELETE: 'departments.delete',
  },
  positions: {
    VIEW: 'positions.view',
    CREATE: 'positions.create',
    UPDATE: 'positions.update',
    DELETE: 'positions.delete',
  },
  banks: {
    VIEW: 'banks.view',
    UPDATE: 'banks.update',
    DELETE: 'banks.delete',
  },
  employees: {
    VIEW: 'employees.view',
    CREATE: 'employees.create',
    UPDATE: 'employees.update',
    DELETE: 'employees.delete',
    APPROVE: 'employees.approve',
    EXPORT: 'employees.export',
  },
  payrollPeriods: {
    VIEW: 'payrollPeriods.view',
    CREATE: 'payrollPeriods.create',
    UPDATE: 'payrollPeriods.update',
    DELETE: 'payrollPeriods.delete',
    CLOSE: 'payrollPeriods.close',
  },
  salaryConcepts: {
    VIEW: 'salaryConcepts.view',
    CREATE: 'salaryConcepts.create',
    UPDATE: 'salaryConcepts.update',
    DELETE: 'salaryConcepts.delete',
  },
  deductions: {
    VIEW: 'deductions.view',
    CREATE: 'deductions.create',
    UPDATE: 'deductions.update',
    DELETE: 'deductions.delete',
  },
  loans: {
    VIEW: 'loans.view',
    CREATE: 'loans.create',
    UPDATE: 'loans.update',
    DELETE: 'loans.delete',
  },
  socialBenefits: {
    VIEW: 'socialBenefits.view',
    CREATE: 'socialBenefits.create',
    UPDATE: 'socialBenefits.update',
  },
  attendance: {
    VIEW: 'attendance.view',
    CREATE: 'attendance.create',
    UPDATE: 'attendance.update',
    DELETE: 'attendance.delete',
  },
  overtime: {
    VIEW: 'overtime.view',
    CREATE: 'overtime.create',
    UPDATE: 'overtime.update',
    DELETE: 'overtime.delete',
    APPROVE: 'overtime.approve',
  },
  vacations: {
    VIEW: 'vacations.view',
    CREATE: 'vacations.create',
    UPDATE: 'vacations.update',
    DELETE: 'vacations.delete',
    APPROVE: 'vacations.approve',
  },
  leaves: {
    VIEW: 'leaves.view',
    CREATE: 'leaves.create',
    UPDATE: 'leaves.update',
    DELETE: 'leaves.delete',
    APPROVE: 'leaves.approve',
  },
  payrollRuns: {
    VIEW: 'payrollRuns.view',
    CREATE: 'payrollRuns.create',
    UPDATE: 'payrollRuns.update',
    DELETE: 'payrollRuns.delete',
    PROCESS: 'payrollRuns.process',
    APPROVE: 'payrollRuns.approve',
    PAY: 'payrollRuns.pay',
  },
  contractTypes: {
    VIEW: 'contractTypes.view',
    CREATE: 'contractTypes.create',
    UPDATE: 'contractTypes.update',
    DELETE: 'contractTypes.delete',
  },
  payrollConfig: {
    VIEW: 'payrollConfig.view',
    UPDATE: 'payrollConfig.update',
  },
  reports: {
    VIEW: 'reports.view',
    EXPORT: 'reports.export',
  },
} as const

export type PermissionCode = string

export const PERMISSION_CATALOG: Array<{
  code: PermissionCode
  description: string
}> = [
  { code: PERMISSION_MATRIX.users.VIEW, description: 'Ver usuarios' },
  { code: PERMISSION_MATRIX.users.CREATE, description: 'Crear usuarios' },
  {
    code: PERMISSION_MATRIX.users.UPDATE,
    description: 'Actualizar usuarios',
  },
  { code: PERMISSION_MATRIX.users.DELETE, description: 'Eliminar usuarios' },
  {
    code: PERMISSION_MATRIX.users.APPROVE,
    description: 'Aprobar acciones de usuarios',
  },

  {
    code: PERMISSION_MATRIX.departments.VIEW,
    description: 'Ver departamentos',
  },
  {
    code: PERMISSION_MATRIX.departments.CREATE,
    description: 'Crear departamentos',
  },
  {
    code: PERMISSION_MATRIX.departments.UPDATE,
    description: 'Actualizar departamentos',
  },
  {
    code: PERMISSION_MATRIX.departments.DELETE,
    description: 'Eliminar departamentos',
  },

  {
    code: PERMISSION_MATRIX.positions.VIEW,
    description: 'Ver posiciones/cargos',
  },
  {
    code: PERMISSION_MATRIX.positions.CREATE,
    description: 'Crear posiciones/cargos',
  },
  {
    code: PERMISSION_MATRIX.positions.UPDATE,
    description: 'Actualizar posiciones/cargos',
  },
  {
    code: PERMISSION_MATRIX.positions.DELETE,
    description: 'Eliminar posiciones/cargos',
  },

  { code: PERMISSION_MATRIX.banks.VIEW, description: 'Ver catálogo de bancos' },
  { code: PERMISSION_MATRIX.banks.UPDATE, description: 'Actualizar bancos' },
  { code: PERMISSION_MATRIX.banks.DELETE, description: 'Eliminar bancos' },

  { code: PERMISSION_MATRIX.employees.VIEW, description: 'Ver empleados' },
  { code: PERMISSION_MATRIX.employees.CREATE, description: 'Crear empleados' },
  {
    code: PERMISSION_MATRIX.employees.UPDATE,
    description: 'Actualizar empleados',
  },
  {
    code: PERMISSION_MATRIX.employees.DELETE,
    description: 'Eliminar empleados',
  },
  {
    code: PERMISSION_MATRIX.employees.APPROVE,
    description: 'Aprobar cambios de empleados (cédula, etc.)',
  },
  {
    code: PERMISSION_MATRIX.employees.EXPORT,
    description: 'Exportar listado de empleados',
  },

  {
    code: PERMISSION_MATRIX.payrollPeriods.VIEW,
    description: 'Ver períodos de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollPeriods.CREATE,
    description: 'Crear períodos de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollPeriods.UPDATE,
    description: 'Actualizar períodos de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollPeriods.DELETE,
    description: 'Eliminar períodos de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollPeriods.CLOSE,
    description: 'Cerrar/pagar períodos de nómina',
  },

  {
    code: PERMISSION_MATRIX.salaryConcepts.VIEW,
    description: 'Ver conceptos salariales',
  },
  {
    code: PERMISSION_MATRIX.salaryConcepts.CREATE,
    description: 'Crear conceptos salariales',
  },
  {
    code: PERMISSION_MATRIX.salaryConcepts.UPDATE,
    description: 'Actualizar conceptos salariales',
  },
  {
    code: PERMISSION_MATRIX.salaryConcepts.DELETE,
    description: 'Eliminar conceptos salariales',
  },

  {
    code: PERMISSION_MATRIX.deductions.VIEW,
    description: 'Ver deducciones de empleados',
  },
  {
    code: PERMISSION_MATRIX.deductions.CREATE,
    description: 'Crear deducciones de empleados',
  },
  {
    code: PERMISSION_MATRIX.deductions.UPDATE,
    description: 'Actualizar deducciones de empleados',
  },
  {
    code: PERMISSION_MATRIX.deductions.DELETE,
    description: 'Eliminar deducciones de empleados',
  },

  { code: PERMISSION_MATRIX.loans.VIEW, description: 'Ver préstamos' },
  { code: PERMISSION_MATRIX.loans.CREATE, description: 'Registrar préstamos' },
  { code: PERMISSION_MATRIX.loans.UPDATE, description: 'Actualizar préstamos' },
  { code: PERMISSION_MATRIX.loans.DELETE, description: 'Cancelar préstamos' },

  {
    code: PERMISSION_MATRIX.socialBenefits.VIEW,
    description: 'Ver prestaciones sociales',
  },
  {
    code: PERMISSION_MATRIX.socialBenefits.CREATE,
    description: 'Acumular prestaciones sociales',
  },
  {
    code: PERMISSION_MATRIX.socialBenefits.UPDATE,
    description: 'Actualizar prestaciones sociales',
  },

  { code: PERMISSION_MATRIX.attendance.VIEW, description: 'Ver asistencia' },
  {
    code: PERMISSION_MATRIX.attendance.CREATE,
    description: 'Registrar asistencia',
  },
  {
    code: PERMISSION_MATRIX.attendance.UPDATE,
    description: 'Actualizar asistencia',
  },
  {
    code: PERMISSION_MATRIX.attendance.DELETE,
    description: 'Eliminar registro de asistencia',
  },

  { code: PERMISSION_MATRIX.overtime.VIEW, description: 'Ver horas extra' },
  {
    code: PERMISSION_MATRIX.overtime.CREATE,
    description: 'Registrar horas extra',
  },
  {
    code: PERMISSION_MATRIX.overtime.UPDATE,
    description: 'Actualizar horas extra',
  },
  {
    code: PERMISSION_MATRIX.overtime.DELETE,
    description: 'Eliminar horas extra',
  },
  {
    code: PERMISSION_MATRIX.overtime.APPROVE,
    description: 'Aprobar horas extra',
  },

  {
    code: PERMISSION_MATRIX.vacations.VIEW,
    description: 'Ver solicitudes de vacaciones',
  },
  {
    code: PERMISSION_MATRIX.vacations.CREATE,
    description: 'Solicitar vacaciones',
  },
  {
    code: PERMISSION_MATRIX.vacations.UPDATE,
    description: 'Actualizar solicitud de vacaciones',
  },
  {
    code: PERMISSION_MATRIX.vacations.DELETE,
    description: 'Cancelar solicitud de vacaciones',
  },
  {
    code: PERMISSION_MATRIX.vacations.APPROVE,
    description: 'Aprobar solicitudes de vacaciones',
  },

  { code: PERMISSION_MATRIX.leaves.VIEW, description: 'Ver permisos' },
  { code: PERMISSION_MATRIX.leaves.CREATE, description: 'Solicitar permiso' },
  { code: PERMISSION_MATRIX.leaves.UPDATE, description: 'Actualizar permiso' },
  { code: PERMISSION_MATRIX.leaves.DELETE, description: 'Cancelar permiso' },
  { code: PERMISSION_MATRIX.leaves.APPROVE, description: 'Aprobar permisos' },

  {
    code: PERMISSION_MATRIX.payrollRuns.VIEW,
    description: 'Ver cálculos de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollRuns.CREATE,
    description: 'Crear cálculo de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollRuns.UPDATE,
    description: 'Actualizar cálculo de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollRuns.DELETE,
    description: 'Eliminar cálculo de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollRuns.PROCESS,
    description: 'Procesar cálculo de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollRuns.APPROVE,
    description: 'Aprobar cálculo de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollRuns.PAY,
    description: 'Marcar nómina como pagada',
  },

  {
    code: PERMISSION_MATRIX.contractTypes.VIEW,
    description: 'Ver tipos de contrato',
  },
  {
    code: PERMISSION_MATRIX.contractTypes.CREATE,
    description: 'Crear tipos de contrato',
  },
  {
    code: PERMISSION_MATRIX.contractTypes.UPDATE,
    description: 'Actualizar tipos de contrato',
  },
  {
    code: PERMISSION_MATRIX.contractTypes.DELETE,
    description: 'Eliminar tipos de contrato',
  },

  {
    code: PERMISSION_MATRIX.payrollConfig.VIEW,
    description: 'Ver configuración de nómina',
  },
  {
    code: PERMISSION_MATRIX.payrollConfig.UPDATE,
    description: 'Actualizar configuración de nómina',
  },

  {
    code: PERMISSION_MATRIX.reports.VIEW,
    description: 'Ver reportes de nómina',
  },
  {
    code: PERMISSION_MATRIX.reports.EXPORT,
    description: 'Exportar reportes',
  },
]

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  OWNER: [
    PERMISSION_MATRIX.users.VIEW,
    PERMISSION_MATRIX.users.CREATE,
    PERMISSION_MATRIX.users.UPDATE,
    PERMISSION_MATRIX.users.DELETE,
    PERMISSION_MATRIX.users.APPROVE,
    PERMISSION_MATRIX.departments.VIEW,
    PERMISSION_MATRIX.departments.CREATE,
    PERMISSION_MATRIX.departments.UPDATE,
    PERMISSION_MATRIX.departments.DELETE,
    PERMISSION_MATRIX.positions.VIEW,
    PERMISSION_MATRIX.positions.CREATE,
    PERMISSION_MATRIX.positions.UPDATE,
    PERMISSION_MATRIX.positions.DELETE,
    PERMISSION_MATRIX.banks.VIEW,
    PERMISSION_MATRIX.banks.UPDATE,
    PERMISSION_MATRIX.banks.DELETE,
    PERMISSION_MATRIX.employees.VIEW,
    PERMISSION_MATRIX.employees.CREATE,
    PERMISSION_MATRIX.employees.UPDATE,
    PERMISSION_MATRIX.employees.DELETE,
    PERMISSION_MATRIX.employees.APPROVE,
    PERMISSION_MATRIX.employees.EXPORT,
    PERMISSION_MATRIX.payrollPeriods.VIEW,
    PERMISSION_MATRIX.payrollPeriods.CREATE,
    PERMISSION_MATRIX.payrollPeriods.UPDATE,
    PERMISSION_MATRIX.payrollPeriods.DELETE,
    PERMISSION_MATRIX.payrollPeriods.CLOSE,
    PERMISSION_MATRIX.salaryConcepts.VIEW,
    PERMISSION_MATRIX.salaryConcepts.CREATE,
    PERMISSION_MATRIX.salaryConcepts.UPDATE,
    PERMISSION_MATRIX.salaryConcepts.DELETE,
    PERMISSION_MATRIX.deductions.VIEW,
    PERMISSION_MATRIX.deductions.CREATE,
    PERMISSION_MATRIX.deductions.UPDATE,
    PERMISSION_MATRIX.deductions.DELETE,
    PERMISSION_MATRIX.loans.VIEW,
    PERMISSION_MATRIX.loans.CREATE,
    PERMISSION_MATRIX.loans.UPDATE,
    PERMISSION_MATRIX.loans.DELETE,
    PERMISSION_MATRIX.socialBenefits.VIEW,
    PERMISSION_MATRIX.socialBenefits.CREATE,
    PERMISSION_MATRIX.socialBenefits.UPDATE,
    PERMISSION_MATRIX.attendance.VIEW,
    PERMISSION_MATRIX.attendance.CREATE,
    PERMISSION_MATRIX.attendance.UPDATE,
    PERMISSION_MATRIX.attendance.DELETE,
    PERMISSION_MATRIX.overtime.VIEW,
    PERMISSION_MATRIX.overtime.CREATE,
    PERMISSION_MATRIX.overtime.UPDATE,
    PERMISSION_MATRIX.overtime.DELETE,
    PERMISSION_MATRIX.overtime.APPROVE,
    PERMISSION_MATRIX.vacations.VIEW,
    PERMISSION_MATRIX.vacations.CREATE,
    PERMISSION_MATRIX.vacations.UPDATE,
    PERMISSION_MATRIX.vacations.DELETE,
    PERMISSION_MATRIX.vacations.APPROVE,
    PERMISSION_MATRIX.leaves.VIEW,
    PERMISSION_MATRIX.leaves.CREATE,
    PERMISSION_MATRIX.leaves.UPDATE,
    PERMISSION_MATRIX.leaves.DELETE,
    PERMISSION_MATRIX.leaves.APPROVE,
    PERMISSION_MATRIX.payrollRuns.VIEW,
    PERMISSION_MATRIX.payrollRuns.CREATE,
    PERMISSION_MATRIX.payrollRuns.UPDATE,
    PERMISSION_MATRIX.payrollRuns.DELETE,
    PERMISSION_MATRIX.payrollRuns.PROCESS,
    PERMISSION_MATRIX.payrollRuns.APPROVE,
    PERMISSION_MATRIX.payrollRuns.PAY,
    PERMISSION_MATRIX.contractTypes.VIEW,
    PERMISSION_MATRIX.contractTypes.CREATE,
    PERMISSION_MATRIX.contractTypes.UPDATE,
    PERMISSION_MATRIX.contractTypes.DELETE,
    PERMISSION_MATRIX.payrollConfig.VIEW,
    PERMISSION_MATRIX.payrollConfig.UPDATE,
    PERMISSION_MATRIX.reports.VIEW,
    PERMISSION_MATRIX.reports.EXPORT,
  ],
  ADMIN: [
    PERMISSION_MATRIX.users.VIEW,
    PERMISSION_MATRIX.users.CREATE,
    PERMISSION_MATRIX.users.UPDATE,
    PERMISSION_MATRIX.users.APPROVE,
    PERMISSION_MATRIX.departments.VIEW,
    PERMISSION_MATRIX.departments.CREATE,
    PERMISSION_MATRIX.departments.UPDATE,
    PERMISSION_MATRIX.departments.DELETE,
    PERMISSION_MATRIX.positions.VIEW,
    PERMISSION_MATRIX.positions.CREATE,
    PERMISSION_MATRIX.positions.UPDATE,
    PERMISSION_MATRIX.positions.DELETE,
    PERMISSION_MATRIX.banks.VIEW,
    PERMISSION_MATRIX.banks.UPDATE,
    PERMISSION_MATRIX.employees.VIEW,
    PERMISSION_MATRIX.employees.CREATE,
    PERMISSION_MATRIX.employees.UPDATE,
    PERMISSION_MATRIX.employees.DELETE,
    PERMISSION_MATRIX.employees.APPROVE,
    PERMISSION_MATRIX.employees.EXPORT,
    PERMISSION_MATRIX.payrollPeriods.VIEW,
    PERMISSION_MATRIX.payrollPeriods.CREATE,
    PERMISSION_MATRIX.payrollPeriods.UPDATE,
    PERMISSION_MATRIX.payrollPeriods.DELETE,
    PERMISSION_MATRIX.payrollPeriods.CLOSE,
    PERMISSION_MATRIX.salaryConcepts.VIEW,
    PERMISSION_MATRIX.salaryConcepts.CREATE,
    PERMISSION_MATRIX.salaryConcepts.UPDATE,
    PERMISSION_MATRIX.salaryConcepts.DELETE,
    PERMISSION_MATRIX.deductions.VIEW,
    PERMISSION_MATRIX.deductions.CREATE,
    PERMISSION_MATRIX.deductions.UPDATE,
    PERMISSION_MATRIX.deductions.DELETE,
    PERMISSION_MATRIX.loans.VIEW,
    PERMISSION_MATRIX.loans.CREATE,
    PERMISSION_MATRIX.loans.UPDATE,
    PERMISSION_MATRIX.loans.DELETE,
    PERMISSION_MATRIX.attendance.VIEW,
    PERMISSION_MATRIX.attendance.CREATE,
    PERMISSION_MATRIX.attendance.UPDATE,
    PERMISSION_MATRIX.socialBenefits.VIEW,
    PERMISSION_MATRIX.socialBenefits.CREATE,
    PERMISSION_MATRIX.socialBenefits.UPDATE,
    PERMISSION_MATRIX.attendance.DELETE,
    PERMISSION_MATRIX.overtime.VIEW,
    PERMISSION_MATRIX.overtime.CREATE,
    PERMISSION_MATRIX.overtime.UPDATE,
    PERMISSION_MATRIX.overtime.DELETE,
    PERMISSION_MATRIX.overtime.APPROVE,
    PERMISSION_MATRIX.vacations.VIEW,
    PERMISSION_MATRIX.vacations.CREATE,
    PERMISSION_MATRIX.vacations.UPDATE,
    PERMISSION_MATRIX.vacations.DELETE,
    PERMISSION_MATRIX.vacations.APPROVE,
    PERMISSION_MATRIX.leaves.VIEW,
    PERMISSION_MATRIX.leaves.CREATE,
    PERMISSION_MATRIX.leaves.UPDATE,
    PERMISSION_MATRIX.leaves.DELETE,
    PERMISSION_MATRIX.leaves.APPROVE,
    PERMISSION_MATRIX.payrollRuns.VIEW,
    PERMISSION_MATRIX.payrollRuns.CREATE,
    PERMISSION_MATRIX.payrollRuns.UPDATE,
    PERMISSION_MATRIX.payrollRuns.DELETE,
    PERMISSION_MATRIX.payrollRuns.PROCESS,
    PERMISSION_MATRIX.payrollRuns.APPROVE,
    PERMISSION_MATRIX.payrollRuns.PAY,
    PERMISSION_MATRIX.contractTypes.VIEW,
    PERMISSION_MATRIX.contractTypes.CREATE,
    PERMISSION_MATRIX.contractTypes.UPDATE,
    PERMISSION_MATRIX.contractTypes.DELETE,
    PERMISSION_MATRIX.payrollConfig.VIEW,
    PERMISSION_MATRIX.payrollConfig.UPDATE,
    PERMISSION_MATRIX.reports.VIEW,
    PERMISSION_MATRIX.reports.EXPORT,
  ],
  GERENTE: [
    PERMISSION_MATRIX.users.VIEW,
    PERMISSION_MATRIX.departments.VIEW,
    PERMISSION_MATRIX.departments.CREATE,
    PERMISSION_MATRIX.departments.UPDATE,
    PERMISSION_MATRIX.positions.VIEW,
    PERMISSION_MATRIX.positions.CREATE,
    PERMISSION_MATRIX.positions.UPDATE,
    PERMISSION_MATRIX.banks.VIEW,
    PERMISSION_MATRIX.employees.VIEW,
    PERMISSION_MATRIX.employees.CREATE,
    PERMISSION_MATRIX.employees.UPDATE,
    PERMISSION_MATRIX.employees.EXPORT,
    PERMISSION_MATRIX.payrollPeriods.VIEW,
    PERMISSION_MATRIX.payrollPeriods.CREATE,
    PERMISSION_MATRIX.payrollPeriods.UPDATE,
    PERMISSION_MATRIX.payrollPeriods.CLOSE,
    PERMISSION_MATRIX.salaryConcepts.VIEW,
    PERMISSION_MATRIX.deductions.VIEW,
    PERMISSION_MATRIX.loans.VIEW,
    PERMISSION_MATRIX.socialBenefits.VIEW,
    PERMISSION_MATRIX.attendance.VIEW,
    PERMISSION_MATRIX.overtime.VIEW,
    PERMISSION_MATRIX.overtime.APPROVE,
    PERMISSION_MATRIX.vacations.VIEW,
    PERMISSION_MATRIX.vacations.APPROVE,
    PERMISSION_MATRIX.leaves.VIEW,
    PERMISSION_MATRIX.leaves.APPROVE,
    PERMISSION_MATRIX.payrollRuns.VIEW,
    PERMISSION_MATRIX.payrollRuns.PROCESS,
    PERMISSION_MATRIX.payrollRuns.APPROVE,
    PERMISSION_MATRIX.contractTypes.VIEW,
    PERMISSION_MATRIX.payrollConfig.VIEW,
    PERMISSION_MATRIX.reports.VIEW,
    PERMISSION_MATRIX.reports.EXPORT,
  ],
  ALMACENISTA: [
    PERMISSION_MATRIX.users.VIEW,
    PERMISSION_MATRIX.banks.VIEW,
    PERMISSION_MATRIX.employees.VIEW,
    PERMISSION_MATRIX.payrollPeriods.VIEW,
    PERMISSION_MATRIX.attendance.VIEW,
    PERMISSION_MATRIX.attendance.CREATE,
    PERMISSION_MATRIX.attendance.UPDATE,
  ],
  VENDEDOR: [
    PERMISSION_MATRIX.users.VIEW,
    PERMISSION_MATRIX.banks.VIEW,
    PERMISSION_MATRIX.employees.VIEW,
    PERMISSION_MATRIX.payrollPeriods.VIEW,
  ],
  VIEWER: [
    PERMISSION_MATRIX.users.VIEW,
    PERMISSION_MATRIX.departments.VIEW,
    PERMISSION_MATRIX.positions.VIEW,
    PERMISSION_MATRIX.banks.VIEW,
    PERMISSION_MATRIX.employees.VIEW,
    PERMISSION_MATRIX.payrollPeriods.VIEW,
    PERMISSION_MATRIX.salaryConcepts.VIEW,
    PERMISSION_MATRIX.deductions.VIEW,
    PERMISSION_MATRIX.loans.VIEW,
    PERMISSION_MATRIX.attendance.VIEW,
    PERMISSION_MATRIX.overtime.VIEW,
    PERMISSION_MATRIX.vacations.VIEW,
    PERMISSION_MATRIX.leaves.VIEW,
    PERMISSION_MATRIX.payrollRuns.VIEW,
    PERMISSION_MATRIX.contractTypes.VIEW,
    PERMISSION_MATRIX.payrollConfig.VIEW,
    PERMISSION_MATRIX.reports.VIEW,
  ],
}
