import { PERMISSION_MATRIX } from './permissionRegistry.js'

export const PERMISSIONS = {
  USERS_VIEW: PERMISSION_MATRIX.users.VIEW,
  USERS_CREATE: PERMISSION_MATRIX.users.CREATE,
  USERS_UPDATE: PERMISSION_MATRIX.users.UPDATE,
  USERS_DELETE: PERMISSION_MATRIX.users.DELETE,
  USERS_APPROVE: PERMISSION_MATRIX.users.APPROVE,

  DEPARTMENTS_VIEW: PERMISSION_MATRIX.departments.VIEW,
  DEPARTMENTS_CREATE: PERMISSION_MATRIX.departments.CREATE,
  DEPARTMENTS_UPDATE: PERMISSION_MATRIX.departments.UPDATE,
  DEPARTMENTS_DELETE: PERMISSION_MATRIX.departments.DELETE,

  POSITIONS_VIEW: PERMISSION_MATRIX.positions.VIEW,
  POSITIONS_CREATE: PERMISSION_MATRIX.positions.CREATE,
  POSITIONS_UPDATE: PERMISSION_MATRIX.positions.UPDATE,
  POSITIONS_DELETE: PERMISSION_MATRIX.positions.DELETE,

  BANKS_VIEW: PERMISSION_MATRIX.banks.VIEW,
  BANKS_UPDATE: PERMISSION_MATRIX.banks.UPDATE,
  BANKS_DELETE: PERMISSION_MATRIX.banks.DELETE,

  EMPLOYEES_VIEW: PERMISSION_MATRIX.employees.VIEW,
  EMPLOYEES_CREATE: PERMISSION_MATRIX.employees.CREATE,
  EMPLOYEES_UPDATE: PERMISSION_MATRIX.employees.UPDATE,
  EMPLOYEES_DELETE: PERMISSION_MATRIX.employees.DELETE,
  EMPLOYEES_APPROVE: PERMISSION_MATRIX.employees.APPROVE,
  EMPLOYEES_EXPORT: PERMISSION_MATRIX.employees.EXPORT,

  REPORTS_EXPORT: PERMISSION_MATRIX.reports.EXPORT,
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
